# Generated by Django 4.1.4 on 2023-02-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0003_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
